language: python
# command to install dependencies
install: "make"
# command to run tests
script:
  - make all-tests
cache: pip
jobs:
  include:
    - stage: test
      python: '3.5'
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'
    - stage: coverage
      python: '3.7'
      script: codecov