# This is a basic workflow to help you get started with Actions

name: Merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ['3.7', '3.8']

    # Install dependencies
    - name: Install tox and coverage
      run: pip install tox coverage

    # Runs Python tests
    - name: Run Python tests 3.6
      run: make py36-tests

    - name: Run Python tests 3.7
      run: make py37-tests

    - name: Run Python tests 3.8
      run: make py38-tests

    # Uploads the coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        name: coverage
        fail_ci_if_error: true
