
name: Test_PyPI

on:
  push:
    branches: [ master ]
    paths:
      - 'ownca/__version__.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requirements
      run: python -m pip install build

    - name: Build the distribution
      run: python -m build

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/